# Generated by Django 5.1.1 on 2024-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('regular', 'Regular Work Day')], default='regular', max_length=10),
        ),
    ]
