# Generated by Django 5.1.1 on 2024-09-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_clientbillingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingrecord',
            name='company_address',
            field=models.TextField(default='Your Company Address'),
        ),
        migrations.AddField(
            model_name='clientbillingrecord',
            name='company_email',
            field=models.EmailField(default='yourcompany@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='clientbillingrecord',
            name='company_name',
            field=models.CharField(default='Your Company Name', max_length=255),
        ),
        migrations.AddField(
            model_name='clientbillingrecord',
            name='company_phone',
            field=models.CharField(default='Your Company Phone', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.clientbillingrecord')),
            ],
        ),
    ]
