# Generated by Django 5.1.1 on 2024-09-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_clientbillingrecord_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingrecord',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='clientbillingrecord',
            name='invoice_number',
            field=models.CharField(default='0001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientbillingrecord',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
