# Generated by Django 5.1.1 on 2024-09-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_clientbillingrecord_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingrecord',
            name='client_address',
            field=models.TextField(default='Client Address'),
            preserve_default=False,
        ),
    ]
