# Generated by Django 5.1.1 on 2024-09-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_clientbillingrecord_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='clientbillingrecord',
            name='total_amount_owed',
        ),
    ]
