# Generated by Django 5.1.1 on 2024-09-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_clientbillingrecord_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='ClientBillingRecord',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
