# Generated by Django 5.1.1 on 2024-09-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoiceitem_invoice_and_more'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('PHP', 'Philippine Peso')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('billing_records', models.ManyToManyField(related_name='invoices', to='billing.billingrecord')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientonboarding')),
            ],
        ),
    ]
