# Generated by Django 5.1.1 on 2024-09-27 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
