# Generated by Django 5.1.1 on 2024-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_records',
        ),
    ]
