# Generated by Django 5.1.1 on 2024-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_invoice_billing_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
