# Generated by Django 5.1.1 on 2024-09-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_invoice_client_address_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('PHP', 'Philippine Peso'), ('AUD', 'Australian Dollar')], default='USD', max_length=3),
        ),
    ]
