# Generated by Django 5.1.1 on 2024-09-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_invoice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_name',
        ),
    ]
