# Generated by Django 5.1.1 on 2024-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0014_alter_employee_scheduled_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='', help_text="Client's business name", max_length=255)),
                ('primary_contact_name', models.CharField(blank=True, default='', help_text='Primary contact name', max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text="Client's contact email", max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', help_text="Client's contact phone number", max_length=20)),
                ('address', models.CharField(blank=True, default='', help_text="Client's business address", max_length=255)),
                ('seo_type', models.CharField(blank=True, default='', help_text='Local or international SEO type', max_length=50)),
                ('target_goals', models.TextField(blank=True, default='', help_text='Primary SEO goals')),
                ('primary_products_services', models.TextField(blank=True, default='', help_text='Main products or services')),
                ('target_audience', models.TextField(blank=True, default='', help_text='Description of the target audience')),
                ('target_locations', models.TextField(blank=True, default='', help_text='Target locations or regions')),
                ('target_keywords', models.TextField(blank=True, default='', help_text='List of target keywords separated by commas')),
                ('competitor_urls', models.TextField(blank=True, default='', help_text='List of competitor URLs separated by commas')),
                ('ga4_login_details', models.TextField(blank=True, default='', help_text='Google Analytics 4 login details')),
                ('google_search_console_login_details', models.TextField(blank=True, default='', help_text='Google Search Console login details')),
                ('website_backend_login_details', models.TextField(blank=True, default='', help_text="Login details for the client's website backend")),
                ('billing_cycle', models.CharField(blank=True, default='monthly', help_text='Billing cycle (e.g., monthly, quarterly)', max_length=50)),
                ('contract_start_date', models.DateField(blank=True, help_text='Start date of the contract', null=True)),
                ('contract_duration', models.CharField(blank=True, default='', help_text='Duration of the contract (e.g., 6 months, 1 year)', max_length=50)),
                ('assigned_employees', models.ManyToManyField(blank=True, help_text='Employees assigned to this client', related_name='clients', to='employees.employee')),
            ],
        ),
    ]
