# Generated by Django 5.1.1 on 2024-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField()),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_goals', models.TextField(blank=True, null=True)),
                ('target_keywords', models.TextField(blank=True, null=True)),
                ('competitor_urls', models.TextField(blank=True, null=True)),
                ('g4a_login', models.CharField(blank=True, max_length=255, null=True)),
                ('google_search_console_login', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_manager_login', models.CharField(blank=True, max_length=255, null=True)),
                ('website_login', models.CharField(blank=True, max_length=255, null=True)),
                ('cms_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
