# Generated by Django 5.1.1 on 2024-10-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='analytics_view_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
