# Generated by Django 5.1.1 on 2024-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_search_console_login_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_contact_name',
        ),
        migrations.AddField(
            model_name='client',
            name='bulk_keywords',
            field=models.TextField(blank=True, default='', help_text='Bulk keywords', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_hours',
            field=models.TextField(blank=True, default='', help_text='Business hours', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.CharField(blank=True, default='', help_text="Client's contact information", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country_specific_urls',
            field=models.TextField(blank=True, default='', help_text='Country-specific URLs', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='current_cms',
            field=models.CharField(blank=True, default='', help_text='Current CMS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_reviews',
            field=models.TextField(blank=True, default='', help_text='Customer reviews', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='google_analytics_access',
            field=models.BooleanField(default=False, help_text='Google Analytics access'),
        ),
        migrations.AddField(
            model_name='client',
            name='google_analytics_login',
            field=models.TextField(blank=True, default='', help_text='Google Analytics login details', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='google_my_business_url',
            field=models.CharField(blank=True, default='', help_text='Google My Business URL', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='google_search_console_details',
            field=models.TextField(blank=True, default='', help_text='Google Search Console login details', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='hreflang_implementation',
            field=models.BooleanField(default=False, help_text='Hreflang implemented for language targeting'),
        ),
        migrations.AddField(
            model_name='client',
            name='international_competitor_websites',
            field=models.TextField(blank=True, default='', help_text='International competitor websites', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='languages_supported',
            field=models.TextField(blank=True, default='', help_text='Languages supported on the website', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Client's business name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_area',
            field=models.TextField(blank=True, default='', help_text='Service area', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='top_competitors',
            field=models.TextField(blank=True, default='', help_text='Top competitors', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default='', help_text="Client's business address", null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_cycle',
            field=models.CharField(blank=True, default='monthly', help_text='Billing cycle (e.g., monthly, yearly)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='competitor_urls',
            field=models.TextField(blank=True, default='', help_text='List of competitor URLs', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_duration',
            field=models.IntegerField(blank=True, default=0, help_text='Contract duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_start_date',
            field=models.DateField(blank=True, default=None, help_text='Contract start date', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Client's contact email", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ga4_login_details',
            field=models.TextField(blank=True, default='', help_text='GA4 login details', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="Client's contact phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_products_services',
            field=models.TextField(blank=True, default='', help_text='Main products or services', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='seo_type',
            field=models.CharField(blank=True, default='Local', help_text='Local or international SEO type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_audience',
            field=models.TextField(blank=True, default='', help_text='Description of the target audience', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_goals',
            field=models.TextField(blank=True, default='', help_text='Primary SEO goals', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_keywords',
            field=models.TextField(blank=True, default='', help_text='Target keywords for SEO', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_locations',
            field=models.TextField(blank=True, default='', help_text='Target locations or regions', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='website_backend_login_details',
            field=models.TextField(blank=True, default='', help_text='Website backend login details', null=True),
        ),
    ]
