# Generated by Django 5.1.1 on 2024-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='other_cms',
            field=models.CharField(blank=True, default='', help_text='Other CMS if selected', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle (e.g., monthly, yearly)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Contract duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Contract start date', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_cms',
            field=models.CharField(blank=True, choices=[('WordPress', 'WordPress'), ('Joomla', 'Joomla'), ('Drupal', 'Drupal'), ('Other', 'Other')], default='', help_text='Current CMS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='google_my_business_url',
            field=models.URLField(blank=True, default='', help_text='Google My Business URL', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='seo_type',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('International', 'International')], default='Local', help_text='Type of SEO service', max_length=20, null=True),
        ),
    ]
