# Generated by Django 5.1.1 on 2024-10-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientonboarding_analytics_view_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientonboarding',
            name='analytics_view_id',
        ),
    ]
