# Generated by Django 5.1.1 on 2024-09-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
