# Generated by Django 5.1.1 on 2024-09-18 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_per_day_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scheduled_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
