# Generated by Django 5.1.1 on 2024-09-18 10:15

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_latenessdeduction_deduction_and_more'),
        ('employees', '0009_employee_lateness_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lateness_rule',
            field=models.ForeignKey(blank=True, help_text='Assign a lateness rule to the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.latenessrule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='per_day_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily rate for the employee. Example: 100.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.png', help_text='Upload a profile picture for the employee.', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scheduled_start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Scheduled start time for the employee. Example: 08:00 AM'),
        ),
    ]
