# Generated by Django 5.1.1 on 2024-09-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_globalsettings_latenessdeduction_description_and_more'),
        ('employees', '0010_alter_employee_lateness_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='123 Default St', help_text='Home address of the employee. Example: 123 Main St, City, Country', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Default City', help_text='City where the employee resides. Example: Manila', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(default='Default Country', help_text='Country where the employee resides. Example: Philippines', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Email address of the employee. Example: jdoe@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Juan', help_text='First name of the employee. Example: Juan', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Dela Cruz', help_text='Last name of the employee. Example: Dela Cruz', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lateness_rule',
            field=models.ForeignKey(blank=True, help_text='Assign a lateness rule to the employee. If not set, the global default rule is applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.latenessrule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name of the employee. Optional.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='Contact phone number of the employee. Example: 09123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Specific scheduled start time for the employee. If not set, global scheduled start time is used. Example: 08:00 AM', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='default_username', help_text='Unique username for the employee. Example: jdoe', max_length=100, unique=True),
        ),
    ]
