# Generated by Django 5.1.1 on 2024-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employee_lateness_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Specific scheduled start time for the employee. If not set, global scheduled start time is used. Example: 18:25 (24-hour format)', null=True),
        ),
    ]
