# Generated by Django 5.1.1 on 2024-09-26 09:17

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_scheduled_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='totp_secret',
            field=models.CharField(default=pyotp.random_base32, help_text='TOTP secret for two-factor authentication', max_length=32),
        ),
    ]
