# Generated by Django 5.1.1 on 2024-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the holiday, e.g., New Year, Christmas.', max_length=100, unique=True)),
                ('date', models.DateField(help_text='Date of the holiday.')),
                ('is_recurring', models.BooleanField(default=False, help_text='Indicates if the holiday recurs annually.')),
                ('holiday_type', models.CharField(choices=[('non_working', 'Non-Working Holiday'), ('special_non_working', 'Special Non-Working Holiday'), ('fixed', 'Fixed Holiday'), ('non_fixed', 'Non-Fixed Holiday')], default='non_working', help_text='Type of the holiday.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the holiday.', null=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
    ]
