# Generated by Django 5.1.1 on 2024-09-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('non_working', 'Non-Working Holiday'), ('special_non_working', 'Special Non-Working Holiday')], default='non_working', help_text='Type of the holiday. "Non-Working" are paid even if not clocked in. "Special Non-Working" require clock-in for pay.', max_length=20),
        ),
    ]
