# Generated by Django 5.1.1 on 2024-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holiday_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the holiday.', null=True),
        ),
    ]
