# Generated by Django 5.1.1 on 2024-09-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='recurring_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The day (1-31) when the holiday recurs. Required for recurring holidays.', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='recurring_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The month (1-12) when the holiday recurs. Required for recurring holidays.', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the holiday. For non-recurring holidays only.', null=True),
        ),
    ]
