# Generated by Django 5.1.1 on 2024-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('google_analytics', 'Google Analytics'), ('keyword_research', 'Keyword Research'), ('website_audit', 'Website Audit'), ('google_search_console', 'Google Search Console')], max_length=50, null=True),
        ),
    ]
