# Generated by Django 5.1.1 on 2024-10-22 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
