# Generated by Django 5.1.1 on 2024-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_sitemap_sitemapurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='canonical_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='current_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='h1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='index_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='inlinks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='last_modified',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='outlinks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(default='text/html; charset=UTF-8', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='url',
            field=models.URLField(default='http://example.com/sitemap.xml'),
        ),
        migrations.AlterField(
            model_name='sitemapurl',
            name='url',
            field=models.URLField(default='http://example.com/page'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='drive_file_id',
            field=models.CharField(default='unknown_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='unknown_file', max_length=255),
        ),
    ]
