# Generated by Django 5.1.1 on 2024-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_uploadedfile_avg_time_on_page_uploadedfile_best_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapurl',
            name='url',
            field=models.URLField(default='http://example.com/page', max_length=1000),
        ),
    ]
