# Generated by Django 5.1.1 on 2024-10-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_uploadedfile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='url',
            field=models.URLField(default='http://example.com', max_length=2000),
        ),
    ]
