# Generated by Django 5.1.1 on 2024-10-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_uploadedfile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, choices=[('product_page', 'Product Page'), ('product_category', 'Product Category'), ('local_lander', 'Local Lander'), ('lead_generation', 'Lead Generation'), ('blog_post', 'Blog Post'), ('resource_guide', 'Resource / Guide'), ('blog_category', 'Blog Category'), ('site_info', 'Site Info'), ('images', 'Images'), ('assets', 'Assets')], max_length=50, null=True),
        ),
    ]
