# Generated by Django 5.1.1 on 2024-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='action_choice',
            field=models.CharField(blank=True, choices=[('leave', '1. Leave As Is'), ('update_on_page', '2. Update "On Page"'), ('target_with_links', '3. Target w/ Links'), ('301', '4. 301'), ('canonicalize', '5. Canonicalize'), ('block_crawl', '6. Block Crawl'), ('no_index', '7. No Index'), ('content_audit', '8. Content Audit'), ('merge', '9. Merge')], default='leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, choices=[('product_page', '1. Product Page'), ('product_category', '2. Product Category'), ('local_lander', '3. Local Lander'), ('lead_generation', '4. Lead Generation'), ('blog_post', '5. Blog Post'), ('resource_guide', '6. Resource / Guide'), ('blog_category', '7. Blog Category'), ('site_info', '8. Site Info'), ('images', '9. Images'), ('assets', '10. Assets')], default='product_page', max_length=50),
        ),
    ]
