# Generated by Django 5.1.1 on 2024-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_alter_uploadedfile_action_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, choices=[('Product Page', 'Product Page'), ('Product Category', 'Product Category'), ('Local Lander', 'Local Lander'), ('Lead Generation', 'Lead Generation'), ('Blog Post', 'Blog Post'), ('Resource / Guide', 'Resource / Guide'), ('Blog Category', 'Blog Category'), ('Site Info', 'Site Info'), ('Images', 'Images'), ('Assets', 'Assets')], max_length=255, null=True),
        ),
    ]
