# Generated by Django 5.1.1 on 2024-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='avg_time_on_page',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
