# Generated by Django 5.1.1 on 2024-10-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_alter_uploadedfile_losing_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the saved dashboard for easy reference.', max_length=255)),
                ('data', models.TextField(help_text='Serialized data of the dashboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_files', models.ManyToManyField(related_name='dashboards', to='audit.uploadedfile')),
            ],
        ),
    ]
