# Generated by Django 5.1.1 on 2024-10-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_saveddashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDashboard',
        ),
    ]
