# Generated by Django 5.1.1 on 2024-10-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_auditdashboard_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='pk_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='pk_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
