# Generated by Django 5.1.1 on 2024-10-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_uploadedfile_pk_ranking_uploadedfile_pk_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='secondary_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
