# Generated by Django 5.1.1 on 2024-10-23 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_uploadedfile_user'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdashboard',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clientonboarding'),
        ),
    ]
