# Generated by Django 5.1.1 on 2024-10-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_uploadedfile_customer_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
