# Generated by Django 5.1.1 on 2024-10-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_uploadedfile_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='content_type',
            new_name='serp_content_type',
        ),
    ]
