# Generated by Django 5.1.1 on 2024-09-26 04:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0014_alter_employee_scheduled_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pay_period_start', models.DateField(help_text='The start date of the pay period.')),
                ('pay_period_end', models.DateField(help_text='The end date of the pay period.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('date_processed', models.DateField(blank=True, help_text='Date when the payment was processed.', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
