# Generated by Django 5.1.1 on 2024-09-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrecord_payment_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='other_payment_platform',
            field=models.CharField(blank=True, help_text="Custom payment platform if 'Other' is selected.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload proof of payment (receipt or screenshot).', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payment_platform',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('maya', 'Maya'), ('other', 'Other')], help_text='The payment platform used (e.g., GCash, Bank Transfer, Maya, Other).', max_length=50, null=True),
        ),
    ]
