# Generated by Django 5.1.1 on 2024-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_parent_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
