# Generated by Django 5.1.1 on 2024-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0003_menuitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='visibility',
            field=models.ManyToManyField(blank=True, help_text='Select which groups can see this menu item. Leave empty for everyone.', to='auth.group'),
        ),
    ]
