# Generated by Django 5.1.1 on 2024-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu', 'position']},
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
