# Generated by Django 5.1.1 on 2024-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('clocked_in', 'Clocked In'), ('on_break', 'On Break'), ('clocked_out', 'Clocked Out')], default='clocked_out', max_length=20),
        ),
    ]
