# Generated by Django 5.1.1 on 2024-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
