# Generated by Django 5.1.1 on 2024-09-18 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_latenessdeduction_latenessrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lateness',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lateness_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
