# Generated by Django 5.1.1 on 2024-09-18 10:15

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_lateness_attendance_lateness_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latenessdeduction',
            name='deduction',
        ),
        migrations.AddField(
            model_name='latenessdeduction',
            name='deduction_duration',
            field=models.DurationField(default='0:00:00', help_text='Duration to deduct from income due to lateness. Example: 0:02:00 for 2 hours'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_end_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee ended their break.', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_start_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee started their break.', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked in. Example: 2023-01-01 08:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked out. Example: 2023-01-01 17:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lateness',
            field=models.DurationField(blank=True, help_text='Duration the employee was late, calculated based on scheduled start time.', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lateness_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total monetary deduction due to lateness, calculated based on lateness rules.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('clocked_in', 'Clocked In'), ('on_break', 'On Break'), ('clocked_out', 'Clocked Out')], default='clocked_out', help_text='Current status of the employee: Clocked In, On Break, or Clocked Out.', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.FloatField(blank=True, help_text='Total hours worked, calculated automatically.', null=True),
        ),
        migrations.AlterField(
            model_name='latenessdeduction',
            name='min_lateness',
            field=models.DurationField(help_text='Minimum lateness duration to trigger this deduction. Example: 0:05:01 for 5 minutes and 1 second'),
        ),
        migrations.AlterField(
            model_name='latenessrule',
            name='deductions',
            field=models.ManyToManyField(help_text='Select the deductions that apply for this rule based on lateness duration.', to='attendance.latenessdeduction'),
        ),
        migrations.AlterField(
            model_name='latenessrule',
            name='grace_period',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Duration allowed before lateness deductions apply. Example: 0:05:00 for 5 minutes'),
        ),
        migrations.AlterField(
            model_name='latenessrule',
            name='name',
            field=models.CharField(help_text='Name of the lateness rule set. Example: Standard Lateness Policy', max_length=100),
        ),
    ]
