# Generated by Django 5.1.1 on 2024-09-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_latenessdeduction_deduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start_time', models.TimeField(default=datetime.time(8, 0), help_text='Global scheduled start time for all employees. Example: 08:00 AM')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AddField(
            model_name='latenessdeduction',
            name='description',
            field=models.TextField(default='No description provided', help_text='Detailed description of the deduction. Explain how the deduction is calculated and applied.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latenessdeduction',
            name='name',
            field=models.CharField(default='Name of lateness deduction', help_text='Name of the lateness deduction. Example: Minor Lateness Deduction', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latenessrule',
            name='description',
            field=models.TextField(default='Describe lateness rule', help_text='Detailed description of the lateness rule. Explain when and how deductions are applied.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latenessdeduction',
            name='deduction_duration',
            field=models.DurationField(help_text='Duration to deduct from income due to lateness. Example: 0:02:00 for 2 hours'),
        ),
    ]
