# Generated by Django 5.1.1 on 2024-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_globalsettings_latenessdeduction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked in. Example: 2023-01-01 18:30:00', null=True),
        ),
    ]
