# Generated by Django 5.1.1 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_clock_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked in. Example: 2023-01-01 19:47:19', null=True),
        ),
    ]
