# Generated by Django 5.1.1 on 2024-09-18 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_clock_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked in. Example: 2023-01-01 19:56:19', null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='scheduled_start_time',
            field=models.TimeField(default=datetime.time(19, 30), help_text='Global scheduled start time for all employees. Example: 19:30 (24-hour format)'),
        ),
    ]
