# Generated by Django 5.1.1 on 2024-09-19 05:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_is_primary_clock_in_and_more'),
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, help_text='Holiday associated with this attendance record, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income for the attendance record, including holiday adjustments.', max_digits=10),
        ),
    ]
