# Generated by Django 5.1.1 on 2024-10-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_holiday_attendance_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hours worked, calculated automatically.', max_digits=5, null=True),
        ),
    ]
