# Generated by Django 5.1.1 on 2024-10-01 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the employee clocked in. Example: 2023-01-01 09:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='scheduled_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Global scheduled start time for all employees. Example: 09:00 (24-hour format)'),
        ),
    ]
