# Generated by Django 5.1.1 on 2024-10-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendance_clock_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_start_time',
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_time', models.DateTimeField()),
                ('break_end_time', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance')),
            ],
        ),
    ]
